/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author kamil
 */
public class GameJPanel extends javax.swing.JPanel {

    /**
     * table with places where draw x and o
     */
    private char[] board;
    private String sign;
    private String turn;
    private String gameState;
    /**
     * Creates new form GameJPanel
     */
    public GameJPanel() {
        initComponents();
        sign = " ";
        turn = " ";
        gameState = "Oczekiwanie";
        board = new char[9];
        for(int i = 0; i < 9; i++)
            board[i] = '-';
    }
    /**
     * Paint whole graphic from this JPanel
     * @param g parameter to draw on this JPanel
     */
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        drawBoard(g2d);
        drawStrings(g2d);
        g2d.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Draw Board to play Tic Tac Toe
     * @param g2d parameter to draw 
     * 2D graphic on this JPanel
     */
    private void drawBoard(Graphics2D g2d) {
        g2d.setColor(Color.BLACK);
        double width = getWidth(), height = getHeight();
        double fieldWidth = width/4, lineWidth = 5,
                lineShortage = (height + width) / 100;
        g2d.fill(new Rectangle2D.Double(
                fieldWidth, 
                lineShortage, 
                lineWidth, 
                height - lineShortage * 2));
        g2d.fill(new Rectangle2D.Double(
                2 * fieldWidth, 
                lineShortage, 
                lineWidth, 
                height - lineShortage * 2));
        g2d.fill(new Rectangle2D.Double(
                lineShortage, 
                fieldWidth, 
                height - lineShortage * 2, 
                lineWidth));
        g2d.fill(new Rectangle2D.Double(
                lineShortage, 
                2 * fieldWidth, 
                height - lineShortage * 2, 
                lineWidth));
        drawSigns(g2d);
    }
    
    
    /**
     * Draw signs on board
     * @param g2d graphic on this JPanel
     */
    private void drawSigns(Graphics2D g2d){
        Point p;
        int fieldWidth = getWidth() / 4, 
                lineShortage = (getHeight() + getWidth()) / 100;
        int firstFieldCenter = lineShortage + fieldWidth / 2 - 5; // -5 because board lines have 5 pixels width
        for(int i = 0; i < 9; i++){
            p = new Point( firstFieldCenter + fieldWidth * (i % 3), firstFieldCenter + fieldWidth * (i / 3));
            switch(board[i]){
                case 'o':
                    drawO(g2d, p);
                    break;
                case 'x':
                    drawX(g2d, p);
                    break;
            }
        }
    }
    
    
    /**
     * Draw x sign at given point
     * @param g2d graphic on this JPanel
     * @param p center of cross
     */
    private void drawX(Graphics2D g2d, Point p){
        double width = 100, height = 100;
        g2d.draw(new Line2D.Double(
                p.getX() - width / 2, 
                p.getY() - height / 2, 
                p.getX() + width / 2, 
                p.getY() + height / 2));
        g2d.draw(new Line2D.Double(
                p.getX() + width / 2, 
                p.getY() - height / 2, 
                p.getX() - width / 2, 
                p.getY() + height / 2));
    }
    
    
    /**
     * Draw x sign at given point
     * @param g2d graphic on this JPanel
     * @param p center of circle
     */
    private void drawO(Graphics2D g2d, Point p){
        double width = 100, height = 100;
        g2d.draw(new Ellipse2D.Double(
                p.getX() - width / 2, 
                p.getY() - height / 2, 
                width, 
                height));
    }
    
    
    /**
     * @param board the board to set
     */
    public void setBoard(char[] board) {
        this.board = board;
    }
    
    
    public void drawStrings(Graphics2D g2d){
        float width =  getWidth(), height = getHeight();
        g2d.drawString("Twój znak", width - 80, 10);
        g2d.drawString(this.sign, width - 80, 30);
        g2d.drawString("Tura", width - 80, 110);
        g2d.drawString(this.turn, width - 80, 130);
        g2d.drawString(this.gameState, width - 80, 300);
        
    }
    /**
     * @param sign sign on board to set
     * @param place place on baord to set sign in range <0, 8>
     */
    public void setSign(char sign, int place) {
        this.board[place] = sign;
    }
    
    
    /**
     * @param sign the sign to set
     */
    public void setSign(String sign) {
        if("n".equals(sign))
            sign = " ";
        this.sign = sign;
    }

    /**
     * @param turn the turn to set
     */
    public void setTurn(String turn) {
        if("n".equals(turn))
            turn = " ";
        this.turn = turn;
    }

    /**
     * @param gameState the gameState to set
     */
    public void setGameState(String gameState) {
        this.gameState = gameState;
    }
}
