/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author kamil
 */
public class GameJPanel extends javax.swing.JPanel {

    /**
     * table with places where draw x and o
     */
    private char[] board;
    /**
     * Creates new form GameJPanel
     */
    public GameJPanel() {
        initComponents();
        board = new char[9];
        for(int i = 0; i < 9; i++)
            board[i] = '-';
    }
    /**
     * Paint whole graphic from this JPanel
     * @param g parameter to draw on this JPanel
     */
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        drawBoard(g2d);
        g2d.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Draw Board to play Tic Tac Toe
     * @param g2d parameter to draw 
     * 2D graphic on this JPanel
     */
    private void drawBoard(Graphics2D g2d) {
        g2d.setColor(Color.BLACK);
        double width = getWidth(), height = getHeight();
        double fieldWidth = width/4, lineWidth = 5,
                lineShortage = (height + width) / 100;
        g2d.fill(new Rectangle2D.Double(
                fieldWidth, 
                lineShortage, 
                lineWidth, 
                height - lineShortage * 2));
        g2d.fill(new Rectangle2D.Double(
                2 * fieldWidth, 
                lineShortage, 
                lineWidth, 
                height - lineShortage * 2));
        g2d.fill(new Rectangle2D.Double(
                lineShortage, 
                fieldWidth, 
                height - lineShortage * 2, 
                lineWidth));
        g2d.fill(new Rectangle2D.Double(
                lineShortage, 
                2 * fieldWidth, 
                height - lineShortage * 2, 
                lineWidth));
    }

    /**
     * @param board the board to set
     */
    public void setBoard(char[] board) {
        this.board = board;
    }
    /**
     * @param sign sign on board to set
     * @param place place on baord to set sign in range <0, 8>
     */
    public void setSign(char sign, int place) {
        this.board[place] = sign;
    }
}
