/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import javax.swing.JPanel;

/**
 *
 * @author kamil
 */
public class MainWindowFrame extends javax.swing.JFrame {
    public JPanel activePanel;
    /**
     * Creates new form MainWindowFrame
     */
    public MainWindowFrame() {
        super("Tic Tac Toe");
        initComponents();
        setLayout(new BorderLayout(0, 0));
        JPanel panel = new GameJPanel();
        add(panel, BorderLayout.CENTER);
        panel.setVisible(true);
        pack();
        setSize(500, 400);
        setResizable(false);
        //activePanel = new GameJPanel();
        //javax.swing.GroupLayout layout = new javax.swing.GroupLayout(activePanel);
        //activePanel.setLayout(layout);
        
        //activePanel.setVisible(true);
        //this.add(activePanel);
        //activePanel.setVisible(true);
        //pack();
        
        /*Graphics g = this.getGraphics();
        System.out.println(g);
        Graphics2D g2d = (Graphics2D) g;
        System.out.println("koloruje Frame");
        System.out.println(this.getWidth());
        g2d.setColor(Color.red);
        g2d.draw(new Line2D.Double(0, 0, 100, 100));
        g2d.setColor(Color.red);
        g2d.fill(new Rectangle2D.Double(
                10, 
                10, 
                100, 
                100));
        g2d.dispose();*/
    }

    /**
     * Swap two JPanels
     * @param newPanel - new Panel to show in JFrame
     */
    public void setActivePanel(GameJPanel newPanel) {
        if(activePanel != null)
            activePanel.setVisible(false);
        activePanel = newPanel;
        activePanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
